version: "2.1"
services:
  chatbot:
    container_name: Chatbot
    image: chatbot
    links:
      - db:db
    depends_on:
      - db
    restart: on-failure
    ports:
      - 9003:5001

  alembic:
    container_name: Chatbot_Alembic
    image: chatbot
    entrypoint: ["alembic", "upgrade", "head"]
    restart: no
    depends_on:
      - db
    links:
      - db:db

  db:
    container_name: Chatbot_DB
    image: postgres
    env_file:
      - .env
    volumes:
      - ${DATA_DIR:-~/.postgres/chatbot}:/var/lib/postgresql/data