"""Mark invalid songs.

Revision ID: 038f072eaa67
Revises: c727d6739f38
Create Date: 2020-04-07 15:09:36.469686

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '038f072eaa67'
down_revision = 'c727d6739f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('valid', sa.Boolean(), server_default='true', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'valid')
    # ### end Alembic commands ###
