"""Timezone aware outgoing messages

Revision ID: 0413ee207d0d
Revises: 10bef045f321
Create Date: 2020-04-02 15:12:47.026399

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0413ee207d0d'
down_revision = '10bef045f321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outgoingmessagemodel', 'send_time', type_=sa.TIMESTAMP(timezone=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outgoingmessagemodel', 'send_time', type_=sa.DateTime())
    # ### end Alembic commands ###
