"""Nickname case insensitive

Revision ID: 093acf74e5bc
Revises: aba1285c70cc
Create Date: 2020-04-02 22:45:11.007193

"""
import sqlalchemy as sa
from alembic import op

from chatbot.database.nickname import NicknameColumn

# revision identifiers, used by Alembic.
revision = '093acf74e5bc'
down_revision = 'aba1285c70cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outgoingmessagemodel', 'send_time', type_=NicknameColumn)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outgoingmessagemodel', 'send_time', type_=sa.String)
    # ### end Alembic commands ###
