"""Incoming messages unique id

Revision ID: 10bef045f321
Revises: cc64276faedc
Create Date: 2020-04-02 14:11:05.040078

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '10bef045f321'
down_revision = 'cc64276faedc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'incomingmessagemodel', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incomingmessagemodel', type_='unique')
    # ### end Alembic commands ###
