"""Renamed ping target

Revision ID: 17f306198218
Revises: c12496276ba2
Create Date: 2020-04-03 18:16:54.586540

"""
import sqlalchemy as sa
from alembic import op
# revision identifiers, used by Alembic.
from sqlalchemy import orm

from chatbot.database.ping import Ping

revision = '17f306198218'
down_revision = 'c12496276ba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ping', sa.Column('target_id', sa.Integer(), nullable=True))

    bind = op.get_bind()
    session = orm.Session(bind=bind)

    try:
        for i in session.query(Ping.target).all():
            if i.target_id is None:
                i.target_id = i.target

        session.commit()
    except:
        session.rollback()
        raise
    finally:
        session.close()

    op.drop_constraint('ping_target_fkey', 'ping', type_='foreignkey')
    op.create_foreign_key(None, 'ping', 'nickname', ['target_id'], ['_column_id'])
    op.drop_column('ping', 'target')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ping', sa.Column('target', sa.INTEGER(), autoincrement=False, nullable=True))

    bind = op.get_bind()
    session = orm.Session(bind=bind)

    try:
        for i in session.query(Ping).all():
            if i.target is None:
                i.target = i.target_id

        session.commit()
    except:
        session.rollback()
    finally:
        session.close()

    op.drop_constraint(None, 'ping', type_='foreignkey')
    op.create_foreign_key('ping_target_fkey', 'ping', 'nickname', ['target'], ['_column_id'])
    op.drop_column('ping', 'target_id')
    # ### end Alembic commands ###
