"""Added original nickname column.

Revision ID: 90443bd32493
Revises: 093acf74e5bc
Create Date: 2020-04-03 00:55:21.598383

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import orm

# revision identifiers, used by Alembic.
from chatbot.database.nickname import Nickname

revision = '90443bd32493'
down_revision = '093acf74e5bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nickname', sa.Column('original', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'nickname', ['original'])

    bind = op.get_bind()
    session = orm.Session(bind=bind)

    for i in session.query(Nickname).all():
        if i.original is None:
            i.original = i.nickname

    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nickname', type_='unique')
    op.drop_column('nickname', 'original')
    # ### end Alembic commands ###
