"""Saving fore- and surname

Revision ID: a036e7242644
Revises: a2b2ae34165f
Create Date: 2020-04-02 18:03:57.091455

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a036e7242644'
down_revision = 'a2b2ae34165f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qedler', sa.Column('forename', sa.String(), nullable=True))
    op.add_column('qedler', sa.Column('surname', sa.String(), nullable=True))
    op.drop_constraint('qedler_user_name_unique', 'qedler', type_='unique')
    op.drop_column('qedler', 'user_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qedler', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('qedler_user_name_unique', 'qedler', ['user_name'])
    op.drop_column('qedler', 'surname')
    op.drop_column('qedler', 'forename')
    # ### end Alembic commands ###
