"""Unique Nickname

Revision ID: aba1285c70cc
Revises: a036e7242644
Create Date: 2020-04-02 22:21:06.390086

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'aba1285c70cc'
down_revision = 'a036e7242644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'nickname', ['nickname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nickname', type_='unique')
    # ### end Alembic commands ###
