"""Ping verification and post_id

Revision ID: c727d6739f38
Revises: 17f306198218
Create Date: 2020-04-03 21:22:30.151796

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c727d6739f38'
down_revision = '17f306198218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ping', sa.Column('post_id', sa.Integer(), nullable=False))
    op.add_column('ping', sa.Column('verified', sa.String(), nullable=True))

    op.create_unique_constraint('ping_post_id_unique', 'ping', ['post_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ping_post_id_unique', 'ping', type_='unique')
    op.drop_column('ping', 'verified')
    op.drop_column('ping', 'post_id')
    # ### end Alembic commands ###
