"""Song DB

Revision ID: cc64276faedc
Revises: d28b73899ae5
Create Date: 2020-04-02 14:09:54.976839

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cc64276faedc'
down_revision = 'd28b73899ae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
                    sa.Column('_column_id', sa.Integer(), nullable=False),
                    sa.Column('video_id', sa.String(), nullable=True),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('_column_id', 'song_column_id_pkey'),
                    sa.UniqueConstraint('video_id', 'song_video_id_unique')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song')
    # ### end Alembic commands ###
